variable "dc_name" {}
variable "datastore_name" {}
variable "nameofcluster" {}
variable "resource_pool" {}
variable "network_name" {}
variable "template_name" {}
variable "buildvm_name" {}
variable "computer_name" {}
variable "join_domain" {}
variable "domain_admin_user" {}
variable "domain_admin_password" {}
variable "admin_password" {}
variable "ipv4_address" {}
variable "dns_server_list" {}
variable "ipv4_gateway" {}
variable "user" {}
#variable "targetresourcepool" {}
variable "num_cpus" {}
variable "memory" {}
variable "disk1" {}
variable "disk2" {}